services:
  CryptoNFT-client:
    image: cryptonft-client
    build:
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.CryptoNFT-client.rule=Host(`nft.mds.mondon.pro`)"
      - "traefik.http.routers.CryptoNFT-client.entrypoints=websecure"
      - "traefik.http.routers.CryptoNFT-client.tls.certresolver=myresolver"